"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.mini_formation_cycle import MiniFormationCycle
from osis_parcours_interne_sdk.model.mobilite_cycle import MobiliteCycle
from osis_parcours_interne_sdk.model.partenariat_cycle import PartenariatCycle
from osis_parcours_interne_sdk.model.total_cycle import TotalCycle
from osis_parcours_interne_sdk.model.tronc_commun_cycle import TroncCommunCycle
globals()['MiniFormationCycle'] = MiniFormationCycle
globals()['MobiliteCycle'] = MobiliteCycle
globals()['PartenariatCycle'] = PartenariatCycle
globals()['TotalCycle'] = TotalCycle
globals()['TroncCommunCycle'] = TroncCommunCycle
from osis_parcours_interne_sdk.model.cycle import Cycle


class TestCycle(unittest.TestCase):
    """Cycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCycle(self):
        """Test Cycle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Cycle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
