"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.complement import Complement
from osis_parcours_interne_sdk.model.cycle import Cycle
from osis_parcours_interne_sdk.model.hors_progression import HorsProgression
globals()['Complement'] = Complement
globals()['Cycle'] = Cycle
globals()['HorsProgression'] = HorsProgression
from osis_parcours_interne_sdk.model.tableau_de_progression import TableauDeProgression


class TestTableauDeProgression(unittest.TestCase):
    """TableauDeProgression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTableauDeProgression(self):
        """Test TableauDeProgression"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TableauDeProgression()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
