"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.api.progression_de_bloc_1_api import ProgressionDeBloc1Api  # noqa: E501


class TestProgressionDeBloc1Api(unittest.TestCase):
    """ProgressionDeBloc1Api unit test stubs"""

    def setUp(self):
        self.api = ProgressionDeBloc1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_progression_de_bloc1(self):
        """Test case for progression_de_bloc1

        """
        pass


if __name__ == '__main__':
    unittest.main()
