"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.api.progression_de_complement_api import ProgressionDeComplementApi  # noqa: E501


class TestProgressionDeComplementApi(unittest.TestCase):
    """ProgressionDeComplementApi unit test stubs"""

    def setUp(self):
        self.api = ProgressionDeComplementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_progression_de_complement(self):
        """Test case for progression_de_complement

        """
        pass


if __name__ == '__main__':
    unittest.main()
