"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.04
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.credits_acquis_mini_formation import CreditsAcquisMiniFormation


class TestCreditsAcquisMiniFormation(unittest.TestCase):
    """CreditsAcquisMiniFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreditsAcquisMiniFormation(self):
        """Test CreditsAcquisMiniFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreditsAcquisMiniFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
