"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.api.proprietes_pae_api import ProprietesPaeApi  # noqa: E501


class TestProprietesPaeApi(unittest.TestCase):
    """ProprietesPaeApi unit test stubs"""

    def setUp(self):
        self.api = ProprietesPaeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_has_une_condition_bama15_ou1adp(self):
        """Test case for has_une_condition_bama15_ou1adp

        """
        pass


if __name__ == '__main__':
    unittest.main()
