"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.barre_progression_bloc1 import BarreProgressionBloc1


class TestBarreProgressionBloc1(unittest.TestCase):
    """BarreProgressionBloc1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBarreProgressionBloc1(self):
        """Test BarreProgressionBloc1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BarreProgressionBloc1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
