"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.02
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.accepted_language_enum import AcceptedLanguageEnum


class TestAcceptedLanguageEnum(unittest.TestCase):
    """AcceptedLanguageEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcceptedLanguageEnum(self):
        """Test AcceptedLanguageEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AcceptedLanguageEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
