"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.02
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.api.progression_api import ProgressionApi  # noqa: E501


class TestProgressionApi(unittest.TestCase):
    """ProgressionApi unit test stubs"""

    def setUp(self):
        self.api = ProgressionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_progression_de_bloc1(self):
        """Test case for get_progression_de_bloc1

        """
        pass

    def test_get_progression_de_complement(self):
        """Test case for get_progression_de_complement

        """
        pass

    def test_get_progression_de_cycle(self):
        """Test case for get_progression_de_cycle

        """
        pass


if __name__ == '__main__':
    unittest.main()
