"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.barre_progression_bloc1 import BarreProgressionBloc1
from osis_parcours_interne_sdk.model.barre_progression_complement import BarreProgressionComplement
from osis_parcours_interne_sdk.model.barre_progression_cycle import BarreProgressionCycle
from osis_parcours_interne_sdk.model.tableau_de_progression import TableauDeProgression
globals()['BarreProgressionBloc1'] = BarreProgressionBloc1
globals()['BarreProgressionComplement'] = BarreProgressionComplement
globals()['BarreProgressionCycle'] = BarreProgressionCycle
globals()['TableauDeProgression'] = TableauDeProgression
from osis_parcours_interne_sdk.model.progression_de_cycle import ProgressionDeCycle


class TestProgressionDeCycle(unittest.TestCase):
    """ProgressionDeCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProgressionDeCycle(self):
        """Test ProgressionDeCycle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProgressionDeCycle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
