"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.05
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_interne_sdk
from osis_parcours_interne_sdk.model.credits_progression_annuelle import CreditsProgressionAnnuelle
globals()['CreditsProgressionAnnuelle'] = CreditsProgressionAnnuelle
from osis_parcours_interne_sdk.model.total_cycle import TotalCycle


class TestTotalCycle(unittest.TestCase):
    """TotalCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTotalCycle(self):
        """Test TotalCycle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TotalCycle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
