# flake8: noqa

"""
    Internal path service

    A set of API endpoints that gives you information about your internal path and progress  # noqa: E501

    The version of the OpenAPI document: 1.02
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.02"

# import ApiClient
from osis_parcours_interne_sdk.api_client import ApiClient

# import Configuration
from osis_parcours_interne_sdk.configuration import Configuration

# import exceptions
from osis_parcours_interne_sdk.exceptions import OpenApiException
from osis_parcours_interne_sdk.exceptions import ApiAttributeError
from osis_parcours_interne_sdk.exceptions import ApiTypeError
from osis_parcours_interne_sdk.exceptions import ApiValueError
from osis_parcours_interne_sdk.exceptions import ApiKeyError
from osis_parcours_interne_sdk.exceptions import ApiException
